Issue #925: Added noncopy constructor for Tensor and TensorT
KomputeProject/kompute pull request #369
Opened 2024-04-17 08:16 UTC by ThePseudo

Added methods reserve() and constructor for Tensor and TensorT

2024-05-29 14:45 UTC, axsaucedo commented
Looks good - only thing would be to add a test, and we can then merge. You can add this on the Tensor test file.

2024-07-20 10:04 UTC, axsaucedo commented
Just following up, do you think you would be able to have a look with a short test @ThePseudo  ?

2024-07-29 06:28 UTC, ThePseudo commented
Sorry for the delay, at some point stuff happened and I lost track of a few things (one being this). I created a short test, which could be expanded upon, but is basically "inspired" by the other test already present. I hope this works!

2024-07-30 11:26 UTC, axsaucedo commented
No worries @ThePseudo, thank you for following up - running test suite

2024-07-30 11:30 UTC, axsaucedo commented
@ThePseudo it seems tests failing, did you run locally?

2024-08-06 14:10 UTC, ThePseudo commented
The terrible thing is that I am not really an expert in the Google test suite... but I found that the tests were failing for a good reason, apparently, and it is building. Which is strange, since "it worked on my machine", but let's try this out

2024-08-06 16:39 UTC, axsaucedo commented on src/include/kompute/Tensor.hpp
> +     * @param newSize the new size for reservation
Docstrings need update as well

2024-08-06 16:41 UTC, axsaucedo requested changes
Thank you @ThePseudo - remaining commment on a small docstring change required

2024-08-17 07:47 UTC, ThePseudo commented
> Thank you @ThePseudo - remaining commment on a small docstring change required

It should be done now, but tell me if the format is not correct (I took inspiration from previous docstrings)

2024-08-17 08:41 UTC, axsaucedo commented on src/include/kompute/Tensor.hpp
> +     * @param newSize the new size for reservation
```suggestion
     * @param elementTotalCount Total number of elements for new size
     * @param elementMemorySize Memory size of element 
```

It has to match the number of parameters, see suggestion

2024-08-17 08:43 UTC, axsaucedo commented
Added extra suggestion as it needs to follow the same format as rest of docstrings

2024-08-18 12:48 UTC, axsaucedo commented
Thank you @ThePseudo - signed commit required, and we should be able to wrap it up :)

2024-08-20 10:13 UTC, ThePseudo commented
> Thank you @ThePseudo - signed commit required, and we should be able to wrap it up :)

Forgot it, now added! :D

2024-08-20 12:23 UTC, axsaucedo commented
Thanks!

2024-08-20 12:23 UTC, merged