Add more information about device to the python bindings
KomputeProject/kompute pull request #406
Opened 2024-12-10 15:36 UTC by koubaa

I encountered the following error 
```
DEBUG:kp:[VALIDATION]: Validation - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08740 ] | MessageID = 0x6e224e9 | vkCreateShaderModule():  SPIR-V Capability Float64 was declared, but one of the following requirements is required (VkPhysicalDeviceFeatures::shaderFloat64).
The Vulkan spec states: If pCode is a pointer to SPIR-V code, and pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08740)
```

So I thought I'd add the ability to check from python whether 64 bit floats are allowed.  I added a few more features that I thought are relevant for kompute (I left the graphics-specific features out).

Alas - kompute reports that 64 bit floats are supported... so I have to debug further why I get this error. But nonetheless I think these changes are worth including.

2024-12-10 15:51 UTC, koubaa commented
ah - that API tells you what features are available. They have to be requested explicitly when creating the device in order to use it. I'll look into that too

2024-12-10 18:57 UTC, koubaa commented
I can't figure out why the python test is crashing. It works on my machine™

2026-04-13 18:20 UTC, axsaucedo requested changes
Thanks, but there's a few additions and changes that I'm not clear why are there - please revisit

2026-04-13 18:20 UTC, axsaucedo commented on python/test/requirements-dev.txt
> +pytest-forked==1.6.0
What is this?

2026-04-13 18:20 UTC, axsaucedo commented on src/include/kompute/Manager.hpp
> +            const vk::PhysicalDeviceFeatures& desiredFeatures,
Why do we need another constructor instead of just adding a new optional param to the previous constructor?

2026-04-13 18:20 UTC, axsaucedo commented on src/Manager.cpp
> +static void setUpLogger() {
Why are we moving this?

2026-04-13 18:20 UTC, axsaucedo commented on Makefile
> +	python3 -m pytest --forked -s --log-cli-level=DEBUG -v python/test/
what is this for?

2026-04-13 18:20 UTC, axsaucedo commented on test/TestAsyncOperations.cpp
> +    kp::Manager mgrAsync(0, std::vector<uint32_t>{ 0, 2 });
why is this needed?

2026-04-13 18:20 UTC, axsaucedo commented on src/Manager.cpp
> -  : Manager(0)
why is this removed?

2026-05-02 08:04 UTC, closed without merging